apiVersion: infra.convee.io/v1alpha1
kind: Package
metadata:
  name: site
spec:
  category: WorkloadPackage
  namespace: sites-local
  namespaceMode: values
  source:
    type: oci
    repoURL: oci://ghcr.io/hullwork/charts/site
    path: .
    renderer: helm
  capabilities:
    requires:
      - kubernetes.api
      - storage.rwo
    provides:
      - sites.control-plane
      - sites.operator
      - sites.build-plane
