/**
* File module: Replace the memory fake backend of the entire API layer when `VITE_USE_MOCK=1`.
*
* Reason for existence: `/v1/admin/*` and `/v1/merchants*` are implemented in parallel by another way, and the UI cannot wait for it.
* Responsibility: Create data according to the **response shape** of contract §4 and support write operations; do not simulate authentication or current limiting.
* Constraints: The data deliberately covers various ugly boundaries - deactivated merchants, Failed phases, missing verification,
* Site with unreachable registry, angle brackets in externally controllable text, and a `javascript:`
*URL. **The malicious URL was intentional**: it caused the "only http/https" guardrail to appear every time
* When running the panel locally, it is actually executed, instead of only existing in the code review memory.
* AI-LOCK: Don't "conveniently change the fake data". Fake data that looks comfortable cannot be proven by any guardrails.
 */

import type { SitesAdminApi } from "./api";
import { SitesApiError } from "./api";
import type {
  AdminBuildView,
  AdminDeploymentView,
  AdminHealthResponse,
  ImageRepositoryView,
  MerchantView,
  TenantView,
  MetricsRange,
  MonitoringResponse,
} from "./types";

const NOW = Date.now();

function iso(minutesAgo: number): string {
  return new Date(NOW - minutesAgo * 60_000).toISOString();
}

/** Fake one-time key. The real value is generated by the server. As long as it looks similar, it will be different every time. */
function fakeSecret(prefix: string): string {
  const random = Array.from({ length: 4 }, () =>
    Math.floor(Math.random() * 0xffffffff).toString(16).padStart(8, "0"),
  ).join("");
  return `${prefix}_${random}`;
}

const merchants: MerchantView[] = [
  {
    merchantId: "local",
    displayName: "Local",
    maxTenants: 20,
    maxDeployments: 40,
    tenantCount: 3,
    deploymentCount: 4,
    createdAt: iso(60 * 24 * 30),
    disabledAt: null,
    keyExpiresAt: iso(-60 * 24 * 20),
    mayActAsSubjects: true,
    // The server always echoes this field; if the mock lacks it, the frontend will respond to a response that is more accurate than the real response.
    // The "loose" shape is developed, and the difference is only exposed when the back end is connected.
    tenantQuota: { cpu: "4", memory: "4Gi", pods: "16" },
  },
  {
    merchantId: "yehang",
    // External controllable text: The display name is always rendered as plain text, and the angle brackets here must appear on the page as they are.
    displayName: "Night Flight <Pictures and Text> Studio",
    maxTenants: 5,
    maxDeployments: 10,
    tenantCount: 2,
    deploymentCount: 2,
    createdAt: iso(60 * 24 * 3),
    disabledAt: null,
    keyExpiresAt: iso(-60 * 24 * 3),
    mayActAsSubjects: false,
    // The server always echoes this field; if the mock lacks it, the frontend will respond to a response that is more accurate than the real response.
    // The "loose" shape is developed, and the difference is only exposed when the back end is connected.
    tenantQuota: { cpu: "4", memory: "4Gi", pods: "16" },
  },
  {
    merchantId: "duomeng",
    displayName: "Duo Meng Education",
    maxTenants: 5,
    maxDeployments: 10,
    tenantCount: 1,
    deploymentCount: 0,
    createdAt: iso(60 * 26),
    disabledAt: iso(90),
    keyExpiresAt: iso(60),
    mayActAsSubjects: false,
    // The server always echoes this field; if the mock lacks it, the frontend will respond to a response that is more accurate than the real response.
    // The "loose" shape is developed, and the difference is only exposed when the back end is connected.
    tenantQuota: { cpu: "4", memory: "4Gi", pods: "16" },
  },
];

const tenants: TenantView[] = [
  {
    merchantId: "local",
    userId: "local",
    maxDeployments: 8,
    maxPublicRoutes: 4,
    createdAt: iso(60 * 24 * 30),
    disabledAt: null,
  },
  {
    merchantId: "local",
    userId: "alice",
    maxDeployments: 4,
    maxPublicRoutes: 2,
    createdAt: iso(60 * 24 * 5),
    disabledAt: null,
  },
  {
    merchantId: "local",
    userId: "bob",
    maxDeployments: 4,
    maxPublicRoutes: 1,
    createdAt: iso(60 * 24 * 2),
    disabledAt: iso(30),
  },
  // The user_id with the same name falls under two merchants: this is exactly what "user_id is only unique within the merchant" looks like,
  // If the table only uses userId as the key, it will collapse into one row here.
  {
    merchantId: "yehang",
    userId: "alice",
    maxDeployments: 6,
    maxPublicRoutes: 2,
    createdAt: iso(60 * 24 * 3),
    disabledAt: null,
  },
  {
    merchantId: "yehang",
    userId: "ops",
    maxDeployments: 2,
    maxPublicRoutes: 0,
    createdAt: iso(60 * 20),
    disabledAt: null,
  },
  {
    merchantId: "duomeng",
    userId: "teacher",
    maxDeployments: 2,
    maxPublicRoutes: 1,
    createdAt: iso(60 * 26),
    disabledAt: null,
  },
];

const deployments: AdminDeploymentView[] = [
  {
    name: "local-local-portfolio-3f2a1c9d8b7e6f50",
    merchantId: "local",
    userId: "local",
    serviceName: "portfolio",
    phase: "Running",
    ready: true,
    runtimeState: "Active",
    scaleToZero: false,
    observedReplicas: 1,
    message: "Deployment ready with 1/1 replicas",
    url: "http://127.0.0.1:18090",
    image: "registry.sites-system.svc:5000/portfolio@sha256:9ab3",
    port: 8080,
    healthPath: "/",
    revision: "1754800000000000000",
    createdAt: iso(60 * 24),
    updatedAt: iso(4),
    verification: {
      ok: true,
      httpStatus: 200,
      bodySha256: "3b1f0c9d77a4e2158cbb0d4a6e9f2c73b8d15e4a0f7c6b93",
    },
    artifactSha256: "c41d8cd98f00b204e9800998ecf8427e1a2b3c4d5e6f7089",
  },
  {
    name: "local-alice-shop-7c1d2e3f4a5b6c7d",
    merchantId: "local",
    userId: "alice",
    serviceName: "shop",
    phase: "Building",
    ready: false,
    message: "BuildKit job running (2/4 steps)",
    url: null,
    image: null,
    port: 3000,
    healthPath: "/healthz",
    createdAt: iso(60 * 3),
    updatedAt: iso(1),
    verification: null,
  },
  {
    name: "local-alice-blog-1a2b3c4d5e6f7a8b",
    merchantId: "local",
    userId: "alice",
    serviceName: "blog",
    phase: "Failed",
    ready: false,
    // External controllable text + line break: The error report copied from the container is entered into this field as it is.
    message:
      'Back-off pulling image "registry.sites-system.svc:5000/blog:latest": ErrImagePull <manifest unknown>',
    url: null,
    image: "registry.sites-system.svc:5000/blog:latest",
    port: 8080,
    healthPath: "/",
    createdAt: iso(60 * 8),
    updatedAt: iso(52),
    verification: { ok: false, httpStatus: 502, error: "connection refused" },
  },
  {
    name: "local-bob-notes-8b7a6c5d4e3f2a1b",
    merchantId: "local",
    userId: "bob",
    serviceName: "notes",
    phase: "Deleting",
    ready: false,
    message: "Sites has been requested to reclaim deployment resources",
    url: null,
    createdAt: iso(60 * 40),
    updatedAt: iso(2),
    deletionRequestedAt: iso(2),
  },
  {
    name: "local-local-docs-9f8e7d6c5b4a3f2e",
    merchantId: "local",
    userId: "local",
    serviceName: "docs",
    phase: "Running",
    ready: true,
    runtimeState: "Dormant",
    scaleToZero: true,
    observedReplicas: 0,
    message: "Scaled to zero by an external autoscaler",
    url: "http://docs.127.0.0.1.sslip.io:18090",
    image: "registry.sites-system.svc:5000/docs:latest",
    port: 8080,
    healthPath: "/",
    revision: "1754801000000000000",
    createdAt: iso(60 * 12),
    updatedAt: iso(3),
    verification: null,
  },
  {
    name: "yehang-alice-landing-2c3d4e5f6a7b8c9d",
    merchantId: "yehang",
    userId: "alice",
    serviceName: "landing",
    phase: "Running",
    ready: true,
    runtimeState: "Active",
    scaleToZero: false,
    observedReplicas: 1,
    message: "Deployment ready with 1/1 replicas",
    // 🔴 Malicious URL: If the control plane returns this for any reason, the link must be downgraded to plain text.
    url: "javascript:alert(document.cookie)",
    image: "registry.sites-system.svc:5000/landing@sha256:11ff",
    port: 80,
    healthPath: "/",
    createdAt: iso(60 * 30),
    updatedAt: iso(9),
    verification: { ok: true, httpStatus: 200, bodySha256: "aa17cc9042e5" },
  },
  {
    name: "yehang-ops-status-4e5f6a7b8c9d0e1f",
    merchantId: "yehang",
    userId: "ops",
    serviceName: "status",
    phase: "Pending",
    ready: false,
    message: "",
    url: null,
    createdAt: iso(12),
    updatedAt: iso(12),
  },
];

const builds: AdminBuildView[] = [
  {
    name: "local-alice-shop-7c1d2e3f4a5b6c7d",
    merchantId: "local",
    userId: "alice",
    serviceName: "shop",
    phase: "Building",
    message: "BuildKit job running (2/4 steps)",
    jobName: "build-local-alice-shop-7c1d2e3f",
    revision: "1754803000000000000",
  },
  {
    name: "local-alice-blog-1a2b3c4d5e6f7a8b",
    merchantId: "local",
    userId: "alice",
    serviceName: "blog",
    phase: "Failed",
    message: 'Dockerfile step 4 failed: npm ERR! 404 Not Found - "@scope/missing"',
    jobName: "build-local-alice-blog-1a2b3c4d",
  },
  {
    name: "yehang-alice-landing-2c3d4e5f6a7b8c9d",
    merchantId: "yehang",
    userId: "alice",
    serviceName: "landing",
    phase: "Running",
    message: "Image pushed to the local registry",
    image: "registry.sites-system.svc:5000/landing",
    imageDigest: "sha256:11ff5c3a9e7b2d4681aa03cd5f9e7b21c4d6a8f03b1e5c7d9a2f4b6e8c0d1a3f",
    jobName: "build-yehang-alice-landing-2c3d4e5f",
  },
];

const images: ImageRepositoryView[] = [
  {
    name: "portfolio",
    tags: [
      { tag: "latest", digest: "sha256:9ab3f0c1d2e3a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5" },
      { tag: "1754800000", digest: "sha256:9ab3f0c1d2e3a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5" },
    ],
  },
  {
    name: "landing",
    tags: [
      { tag: "latest", digest: "sha256:11ff5c3a9e7b2d4681aa03cd5f9e7b21c4d6a8f03b1e5c7d" },
    ],
  },
  // Partially available: The whole repo should not become blank just because a repo cannot list tags.
  { name: "blog", error: "manifest unknown" },
];

const health: AdminHealthResponse = {
  database: { reachable: true, backend: "postgresql", snapshotAgeSeconds: 1.4 },
  operator: { reachable: true, lastReconcileSeconds: 3.1 },
  registry: { reachable: false, error: "dial tcp 10.221.0.42:5000: connect: connection refused" },
  kubernetes: { reachable: true, version: "v1.36.1" },
};

/** Let the loading state and button disabled be visible locally instead of flashing instantly. */
function delay<T>(value: T, ms = 220): Promise<T> {
  return new Promise((resolve) => window.setTimeout(() => resolve(value), ms));
}

function mockMetrics(scope: "cluster" | "application", range: MetricsRange): MonitoringResponse {
  const hours = range === "1h" ? 1 : range === "6h" ? 6 : 24;
  const step = range === "1h" ? 60 : range === "6h" ? 300 : 900;
  const end = Math.floor(Date.now() / 1000);
  const start = end - hours * 3600;
  const values = scope === "cluster" ? [1.18, 932e6, 2.7, 0.38, 44] : [0.08, 76e6, 0.42, 0.12, 31];
  const definitions = [
    ["cpu", "CPU usage", "cores"], ["memory", "memory usage", "bytes"],
    ["requests", "Request rate", "req/s"], ["errors", "4xx / 5xx error rate", "percent"],
    ["latencyP95", "P95 response time", "ms"],
  ] as const;
  const series = definitions.map(([id, label, unit], seriesIndex) => ({
    id, label, unit,
    points: Array.from({ length: Math.floor((end - start) / step) + 1 }, (_, index) => ({
      timestamp: start + index * step,
      value: Math.max(0, (values[seriesIndex] ?? 0) * (1 + 0.16 * Math.sin(index / 4 + seriesIndex))),
    })),
  }));
  const summary: Record<string, number | null> = Object.fromEntries(
    series.map((item) => [item.id, item.points.at(-1)?.value ?? null]),
  );
  if (scope === "cluster") {
    summary.cpuCapacity = 5;
    summary.memoryCapacity = 4.7 * 1024 ** 3;
  }
  return {
    scope, range: { key: range, start, end, stepSeconds: step },
    source: { available: true, sampledAt: new Date().toISOString(), retention: "24h", trafficAvailable: true },
    identity: scope === "application" ? { merchantId: "local", userId: "local", serviceName: "portfolio" } : null,
    summary,
    series,
  };
}

function requireMerchant(merchantId: string): MerchantView {
  const found = merchants.find((item) => item.merchantId === merchantId);
  if (!found) throw new SitesApiError(404, "merchant not found", null);
  return found;
}

function requireTenant(merchantId: string, userId: string): TenantView {
  const found = tenants.find(
    (item) => item.merchantId === merchantId && item.userId === userId,
  );
  if (!found) throw new SitesApiError(404, "tenant not found", null);
  return found;
}

let mockSession = false;

export const mockApi: SitesAdminApi = {
  async logout() {
    mockSession = false;
  },
  async authMethods() {
    return await delay({ oidc: false, localLogin: true });
  },
  async session() {
    await delay(null);
    if (!mockSession) throw new SitesApiError(401, "invalid service token", null);
  },
  async localLogin(token) {
    // There is only one magic value that will be rejected: making the "401 local error" path available locally.
    if (token === "wrong") {
      await delay(null);
      throw new SitesApiError(401, "invalid service token", null);
    }
    await delay(null);
    mockSession = true;
  },

  health: () => delay(health),

  listMerchants: () =>
    delay({ merchants: [...merchants], count: merchants.length }),

  async createMerchant(input) {
    if (merchants.some((item) => item.merchantId === input.merchantId)) {
      throw new SitesApiError(409, "merchant already exists", null);
    }
    merchants.push({
      ...input,
      tenantCount: 0,
      deploymentCount: 0,
      createdAt: new Date().toISOString(),
      disabledAt: null,
    });
    return delay({
      merchantId: input.merchantId,
      displayName: input.displayName,
      maxTenants: input.maxTenants,
      maxDeployments: input.maxDeployments,
      apiKey: fakeSecret("sk-sites"),
      apiKeyShownOnce: true,
    });
  },

  async updateMerchant(merchantId, patch) {
    const record = requireMerchant(merchantId);
    if (patch.displayName !== undefined) record.displayName = patch.displayName;
    if (patch.maxTenants !== undefined) record.maxTenants = patch.maxTenants;
    if (patch.maxDeployments !== undefined) {
      record.maxDeployments = patch.maxDeployments;
    }
    await delay(null);
  },

  async rotateMerchantKey(merchantId) {
    const record = requireMerchant(merchantId);
    return delay({
      merchantId: record.merchantId,
      apiKey: fakeSecret("sk-sites"),
      apiKeyShownOnce: true,
    });
  },

  async disableMerchant(merchantId) {
    requireMerchant(merchantId).disabledAt = new Date().toISOString();
    await delay(null);
  },

  listTenants(merchantId) {
    const rows = merchantId
      ? tenants.filter((item) => item.merchantId === merchantId)
      : tenants;
    return delay({ tenants: [...rows], count: rows.length });
  },

  async createTenant(input) {
    const exists = tenants.some(
      (item) =>
        item.merchantId === input.merchantId && item.userId === input.userId,
    );
    if (exists) throw new SitesApiError(409, "tenant already exists", null);
    requireMerchant(input.merchantId);
    tenants.push({
      ...input,
      createdAt: new Date().toISOString(),
      disabledAt: null,
    });
    return delay({
      merchantId: input.merchantId,
      userId: input.userId,
      token: fakeSecret("st-sites"),
      maxDeployments: input.maxDeployments,
      maxPublicRoutes: input.maxPublicRoutes,
      note: "store this token now; it is not recoverable",
    });
  },

  async updateTenant(merchantId, userId, patch) {
    const record = requireTenant(merchantId, userId);
    if (patch.maxDeployments !== undefined) {
      record.maxDeployments = patch.maxDeployments;
    }
    if (patch.maxPublicRoutes !== undefined) {
      record.maxPublicRoutes = patch.maxPublicRoutes;
    }
    await delay(null);
  },

  async rotateTenantToken(merchantId, userId) {
    const record = requireTenant(merchantId, userId);
    const reenabled = record.disabledAt !== null;
    record.disabledAt = null;
    return delay({
      merchantId,
      userId,
      token: fakeSecret("st-sites"),
      reenabled,
      note: "store this token now; it is not recoverable",
    });
  },

  async disableTenant(merchantId, userId) {
    requireTenant(merchantId, userId).disabledAt = new Date().toISOString();
    await delay(null);
  },

  listDeployments(query) {
    let rows = [...deployments];
    if (query.merchantId) {
      rows = rows.filter((item) => item.merchantId === query.merchantId);
    }
    if (query.phase) rows = rows.filter((item) => item.phase === query.phase);
    if (query.limit) rows = rows.slice(0, query.limit);
    return delay({
      deployments: rows,
      count: rows.length,
      snapshotAgeSeconds: 2.3,
    });
  },

  async createDeployment(input) {
    requireMerchant(input.merchantId);
    requireTenant(input.merchantId, input.userId);
    const existing = deployments.find((item) =>
      item.merchantId === input.merchantId
      && item.userId === input.userId
      && item.serviceName === input.name);
    const row: AdminDeploymentView = {
      ...(existing ?? {}),
      name: existing?.name ?? `${input.merchantId}-${input.userId}-${input.name}-mock`,
      merchantId: input.merchantId,
      userId: input.userId,
      serviceName: input.name,
      image: input.image,
      port: input.port,
      healthPath: input.healthPath,
      exposure: input.exposure,
      memoryLimit: input.memoryLimit ?? "512Mi",
      phase: "Pending",
      ready: false,
      runtimeState: "Unknown",
      message: "Accepted by sites-api",
      url: null,
      updatedAt: new Date().toISOString(),
      createdAt: existing?.createdAt ?? new Date().toISOString(),
    };
    if (existing) Object.assign(existing, row);
    else deployments.unshift(row);
    return delay(row);
  },

  async deleteDeployment(merchantId, userId, serviceName) {
    const found = deployments.find((item) =>
      item.merchantId === merchantId
      && item.userId === userId
      && item.serviceName === serviceName);
    if (found) {
      found.phase = "Deleting";
      found.ready = false;
      found.message = "Deletion requested through sites-api";
      found.updatedAt = new Date().toISOString();
    }
    await delay(null);
  },

  listBuilds(merchantId) {
    const rows = merchantId
      ? builds.filter((item) => item.merchantId === merchantId)
      : builds;
    return delay({ builds: [...rows], count: rows.length });
  },

  // It says here that the registry is reachable, but the health above says it's not reachable - a static fixture cannot.
  // The "image table" and "registry unreachable banner" are displayed at the same time, so the two endpoints are deliberately played half way.
  // If you want to see the banner, translate the following line into `{ reachable: false, error: "..." }`.
  listImages: () =>
    delay({
      repositories: [...images],
      count: images.length,
      registry: { reachable: true },
    }),
  getClusterMetrics: (range) => delay(mockMetrics("cluster", range)),
  getApplicationMetrics: (_identity, range) => delay(mockMetrics("application", range)),
};
